
name: OpenAPI

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  openapi:
    # Name the Job
    name: Host openapi spec
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Generate Swagger UI
         uses: Legion2/swagger-ui-action@v1
         with:
          output: swagger-ui
          spec-file: ./petstore-openapi.yaml
          
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui

       - name: Spec
         uses: actions/upload-artifact@v2
         with:
          name: spec
          path: ./petstore-openapi.yaml